### ISSUE TITLE
OTFVis getting uncaught Exception in Thread AWT-EventQueue-0

### ISSUE THREAD

**Issue by kt86** [matsim-org/matsim-code-examples#648]
As shown in the advanced class today, I am getting an Exception when using OTFVis.

Java Version is 11.
MATSim Version is 13.0
OS: MacOS BigSur (v 11.6)

2021-11-15T15:45:42,628 ERROR MatsimRuntimeModifications$1:62 Getting uncaught Exception in Thread AWT-EventQueue-0
com.jogamp.opengl.GLException: Caught IllegalAccessError: class org.matsim.vis.otfvis.handler.OTFLinkAgentsHandler (in unnamed module @0x6d2260db) cannot access class com.jogamp.opengl.util.texture.TextureCoords (in module jogl.all) because module jogl.all does not export com.jogamp.opengl.util.texture to unnamed module @0x6d2260db on thread AWT-EventQueue-0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76) ~[jogl.all:?]
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327) ~[jogl.all:?]
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147) ~[jogl.all:?]
	at com.jogamp.opengl.awt.GLCanvas$12.run(GLCanvas.java:1442) ~[jogl.all:?]
	at com.jogamp.opengl.Threading.invoke(Threading.java:223) ~[jogl.all:?]
	at com.jogamp.opengl.awt.GLCanvas.display(GLCanvas.java:503) ~[jogl.all:?]
	at com.jogamp.opengl.awt.GLCanvas.paint(GLCanvas.java:557) ~[jogl.all:?]
	at sun.awt.RepaintArea.paintComponent(RepaintArea.java:264) ~[?:?]
	at sun.lwawt.LWRepaintArea.paintComponent(LWRepaintArea.java:59) ~[?:?]
	at sun.awt.RepaintArea.paint(RepaintArea.java:240) ~[?:?]
	at sun.lwawt.LWComponentPeer.handleJavaPaintEvent(LWComponentPeer.java:1317) ~[?:?]
	at sun.lwawt.LWComponentPeer.handleEvent(LWComponentPeer.java:1198) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5088) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4859) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:727) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:751) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:749) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:748) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
Caused by: java.lang.IllegalAccessError: class org.matsim.vis.otfvis.handler.OTFLinkAgentsHandler (in unnamed module @0x6d2260db) cannot access class com.jogamp.opengl.util.texture.TextureCoords (in module jogl.all) because module jogl.all does not export com.jogamp.opengl.util.texture to unnamed module @0x6d2260db
	at org.matsim.vis.otfvis.handler.OTFLinkAgentsHandler.drawLink(OTFLinkAgentsHandler.java:222) ~[otfvis-13.0.jar:?]
	at org.matsim.vis.otfvis.opengl.layer.OGLSimpleStaticNetLayer$1.execute(OGLSimpleStaticNetLayer.java:98) ~[otfvis-13.0.jar:?]
	at org.matsim.vis.otfvis.opengl.layer.OGLSimpleStaticNetLayer$1.execute(OGLSimpleStaticNetLayer.java:94) ~[otfvis-13.0.jar:?]
	at org.matsim.core.utils.collections.QuadTree$Node.execute(QuadTree.java:937) ~[matsim-13.0.jar:?]
	at org.matsim.core.utils.collections.QuadTree.execute(QuadTree.java:228) ~[matsim-13.0.jar:?]
	at org.matsim.vis.otfvis.opengl.layer.OGLSimpleStaticNetLayer.checkNetList(OGLSimpleStaticNetLayer.java:94) ~[otfvis-13.0.jar:?]
	at org.matsim.vis.otfvis.opengl.layer.OGLSimpleStaticNetLayer.init(OGLSimpleStaticNetLayer.java:63) ~[otfvis-13.0.jar:?]
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:644) ~[jogl.all:?]
	at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:667) ~[jogl.all:?]
	at com.jogamp.opengl.awt.GLCanvas$10.run(GLCanvas.java:1411) ~[jogl.all:?]
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1291) ~[jogl.all:?]
	... 29 more
2021-11-15T15:45:42,691 ERROR MatsimRuntimeModifications$1:62 Getting uncaught Exception in Thread AWT-EventQueue-0
com.jogamp.opengl.GLException: Caught IllegalAccessError: class org.matsim.vis.otfvis.opengl.drawer.OTFOGLDrawer (in unnamed module @0x6d2260db) cannot access class com.jogamp.opengl.util.awt.TextRenderer (in module jogl.all) because module jogl.all does not export com.jogamp.opengl.util.awt to unnamed module @0x6d2260db on thread AWT-EventQueue-0
	at com.jogamp.opengl.GLException.newGLException(GLException.java:76) ~[jogl.all:?]
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1327) ~[jogl.all:?]
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147) ~[jogl.all:?]
	at com.jogamp.opengl.awt.GLCanvas$12.run(GLCanvas.java:1442) ~[jogl.all:?]
	at com.jogamp.opengl.Threading.invoke(Threading.java:223) ~[jogl.all:?]
	at com.jogamp.opengl.awt.GLCanvas.display(GLCanvas.java:503) ~[jogl.all:?]
	at com.jogamp.opengl.awt.GLCanvas.paint(GLCanvas.java:557) ~[jogl.all:?]
	at com.jogamp.opengl.awt.GLCanvas.update(GLCanvas.java:870) ~[jogl.all:?]
	at sun.awt.RepaintArea.updateComponent(RepaintArea.java:255) ~[?:?]
	at sun.lwawt.LWRepaintArea.updateComponent(LWRepaintArea.java:47) ~[?:?]
	at sun.awt.RepaintArea.paint(RepaintArea.java:232) ~[?:?]
	at sun.lwawt.LWComponentPeer.handleJavaPaintEvent(LWComponentPeer.java:1317) ~[?:?]
	at sun.lwawt.LWComponentPeer.handleEvent(LWComponentPeer.java:1198) ~[?:?]
	at java.awt.Component.dispatchEventImpl(Component.java:5088) ~[?:?]
	at java.awt.Component.dispatchEvent(Component.java:4859) ~[?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:727) ~[?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:751) ~[?:?]
	at java.awt.EventQueue$5.run(EventQueue.java:749) ~[?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) ~[?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:748) ~[?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
Caused by: java.lang.IllegalAccessError: class org.matsim.vis.otfvis.opengl.drawer.OTFOGLDrawer (in unnamed module @0x6d2260db) cannot access class com.jogamp.opengl.util.awt.TextRenderer (in module jogl.all) because module jogl.all does not export com.jogamp.opengl.util.awt to unnamed module @0x6d2260db
	at org.matsim.vis.otfvis.opengl.drawer.OTFOGLDrawer.init(OTFOGLDrawer.java:465) ~[otfvis-13.0.jar:?]
	at jogamp.opengl.GLDrawableHelper.reshape(GLDrawableHelper.java:749) ~[jogl.all:?]
	at com.jogamp.opengl.awt.GLCanvas$11.run(GLCanvas.java:1424) ~[jogl.all:?]
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293) ~[jogl.all:?]
	... 30 more 

---
Has someone an idea?

**Comment by kainagel** [comment]
This here https://issueexplorer.com/issue/processing/processing4/167 may (or may not) be the same error.  I.e. "version mismatch".  Somewhere.  :-(

**Comment by kainagel** [comment]
Here are my versions, for comparison.  I.e. java version 14.  Language level 8 (which is odd, should be 11, but seems to work).  And a certain version of jogl. 

![image](https://user-images.githubusercontent.com/8777649/141823499-8e1b9e03-8e14-43f9-904e-2d3abe0f0d99.png)

![image](https://user-images.githubusercontent.com/8777649/141824294-59454fef-5af6-45bd-af79-67c99482542e.png)

**Comment by kt86** [comment]
Thanks for the idea with the java version!

Switching back to 11.0.2 also solved the issue
![grafik](https://user-images.githubusercontent.com/12124568/141862946-de52823b-d066-44fb-bce7-acfa1df49293.png)

Before I used 11.0.5 causing the error.
![grafik](https://user-images.githubusercontent.com/12124568/141863011-b3a93568-cea6-4e1e-a5e0-b8ffcd3200dd.png)

--> It is related to the java version (and probably also not only depending on the version number but also from where you have it) :( grrrrr

**Comment by michalmac** [comment]
Ah, I see you used https://confluence.jetbrains.com/display/JBR/JetBrains+Runtime. JBR is mainly meant to run IntelliJ on. Perhaps jogl and JBR are not compatible.

BTW. I recommend switching to the latest JDK 17 :-)

**Comment by kainagel** [comment]
That is strange.

**Comment by kt86** [comment]
Just some more experiences - if other people also have issues

1.) Following the recommendation of @michalmac I tried openjdk**17** (downloaded via IntelliJ)--> has problems with Google injector. :(
Nov. 16, 2021 8:22:53 AM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: java.lang.NoClassDefFoundError: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrapper
java.lang.IllegalStateException: Unable to load cache item
	at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:79)
	at com.google.inject.internal.cglib.core.internal.$LoadingCache.get(LoadingCache.java:34)
	at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
[....]

2.) Since openjdk **14** is not available directly for download in IntelliJ, I downloaded it manually from [https://jdk.java.net/archive/](https://jdk.java.net/archive/)
--> This is working.

**Comment by michalmac** [comment]
> 1.) Following the recommendation of @michalmac I tried openjdk**17** (downloaded via IntelliJ)--> has problems with Google injector. :(

Right. Matsim 13.0 uses an older guice (thus this error), but the 13.x branch is already fixed and works fine with 17.0. Should we maybe release 13.1?

**Comment by kt86** [comment]
Since I (now) also felt into the trap, this seems to me not the worst idea :) - Including an update of the examples-repository to 13.1 as second step
